### ISSUE TITLE
Track-maintainers is empty even though it indicates there are 104 members

### ISSUE THREAD

**Issue by rpottsoh** [exercism/meta#14] opened 2017-07-07 20:27 UTC
This relates to #13 I believe.  While visiting https://github.com/orgs/exercism/teams I see that `track-maintainers` indicates that there are 104 member and 68 teams.  Clicking `68 teams` does nothing even though it is a link.  Clicking `track-maintainers`  reveals a team with zero members and 104 child members and 68 teams.  Clicking on the `child members` or the `68 teams` reveals what had been briefly contained in `track-maintainers` (a week or so ago) and use to be top-level information.

This grouping of track maintainers and their associated tracks with in `track-maintainers` is confusing and makes it more difficult to locate teams and track maintainers.  An extra layer has been introduced that doesn't make it easier to find tracks, but appears to do the opposite.  

I have only been half-following the issues related to this so I apologize if I have only managed to indicate the obvious, otherwise I just wanted to point out how this nesting of teams appears from the outside looking in.

**Comment by iHiD** [comment] 2017-07-07 20:39
> I see that track-maintainers indicates that there are 104 member and 68 teams. Clicking 68 teams does nothing even though it is a link. Clicking track-maintainers reveals a team with zero members and 104 child members and 68 teams. Clicking on the child members or the 68 teams reveals what had been briefly contained in track-maintainers (a week or so ago) and use to be top-level information.

This all sounds like a series of Github bugs/under-developed features, etc more than anything else to me. e.g. I'd also have thought the UI should auto-default to the children tab if the main one is empty. 

The logic for this is in #13 and I think it makes sense to be using Github groups for the purposes of communication, rather than for visibility in the Github UI.

Saying that, we'll be making a much bigger deal of maintainers on the Exercism website soon and that'll be the place that I'd expect people to be looking if they want to find tracks and maintainers, or the place to send people if one want to show Exercism on one's CV.

Thoughts?

**Comment by kytrinyx** [comment] 2017-07-07 20:41
@rpottsoh I don't understand what the problem is here. What is your use case? What are you trying to do? What is the bug?

Previously I had to add people to two teams: track maintainers, and their actual track. Now, by becoming a maintainer of a specific track, you automatically get membership in the track-maintainers team as well, and access to all the repositories.

This makes it easier to maintain. There is a natural relationship between the track maintainers and the child teams. I had people who were maintainers who were not in track-maintainers, and people in track-maintainers who were no longer maintaining any tracks.

**Comment by kytrinyx** [comment] 2017-07-07 20:54
@rpottsoh Ah, I see the 68 teams thing. I've reported it to GitHub Support as that does seem to be a UI bug.

**Comment by rpottsoh** [comment] 2017-07-07 21:00
> Thoughts?  

I like the sound of this.  I think you understand where I am coming from.  

The point I am trying to make is one of perception.  Right now, anyone navigating there way to https://github.com/orgs/exercism/teams is faced with a confusing entry for `track-maintainers`.  I get what the intent of nesting is accomplishing, but the UX is bit of a kludge.....  @kytrinyx I see you just commented while I have been writing this.  I think we're cool.  I agree, that we are looking at a GitHub issue.

**Comment by kytrinyx** [comment] 2017-07-07 21:35
The other point here is that the teams page is about managing the organization, not about public perception. I can't wait until we get the new Exercism website where we make a much bigger deal out of all the people behind Exercism!

**Comment by kytrinyx** [comment] 2017-07-08 01:24
It was, indeed, a bug! It's fixed now. Thanks @rpottsoh for reporting it ✨

**Closed as completed by kytrinyx** 2017-07-08 01:24 UTC
